### ISSUE TITLE
hi, feixue, i have a question about robotcar dataset

### ISSUE THREAD

**Issue by Raywoo1** [feixue94/sfd2#1]
![image](https://github.com/feixue94/sfd2/assets/28223203/00f84880-2026-47c7-8817-ec905c46a344)
In your paper, you use day, night and night-rain. May I ask you a question that, are those files in the image (i.e., sun.zip, night.zip and night-rain.zip)?

**Comment by feixue94** [comment]
day contains all query images captured at day-time inlcluding dawn, dusk, overcast-summer, overcast-winter, rain, snow, and sun. night and night-rain have images from only night.zip and night-rain.zip. Hope this is helpful for you.

**Comment by Raywoo1** [comment]
> 

okok, thanks for the reply. 谢谢你，感恩

**Comment by feixue94** [comment]
加油！一起努力~
