### ISSUE TITLE
Well, i cant find the convnext.pth in google drive.

### ISSUE THREAD

**Issue by Raywoo1** [feixue94/sfd2#2]
hi feixue, me again. I have downloaded the weight file from google drive. However, i cant find the convnext.pth, and, i want to retrain the sfd2.

**Comment by feixue94** [comment]
sorry for late reply. the link for weight of ConvXt is updated as https://drive.google.com/drive/u/1/folders/1bM5lmMFMbsnDe_AdQ6SSs-t2OMIuys_j

**Comment by Raywoo1** [comment]
hahaha, Waiting for a long time. Thank you so so much. Have a good day!
