### ISSUE TITLE
Missing file in the repository

### ISSUE THREAD

**Issue by kkaytekin** [feixue94/sfd2#3]
Hi there,
thanks for open sourcing this work!
I am trying to run your default training script, and I realised the file mentioned [here](https://github.com/feixue94/sfd2/blob/0263c89592814391c856070ac1a868ee0ff50598/nets/semseg/segnet.py#L29) is missing. It is preventing me from running the training script. Ignoring the checkpoint or changing the path to 'weights/convxts-base_ade20k.pth' does not work.
Also, the [pretrained weights from Convext repo ](https://github.com/facebookresearch/ConvNeXt/tree/main/semantic_segmentation) does not seem to have that configuration. Could you please share this file?

**Comment by feixue94** [comment]
Hi,

Weights of convnext and upernet_convnext are uploaded (you can also download the latest version from mmsegmentation).

**Comment by kkaytekin** [comment]
Hello,
thanks for sharing the file! Sadly, as I proceed on my attempt to the run the default training script, I keep running into additional errors.
- I think one main reason is the current setup instructions. The provided `requirements.txt` does not allow to run your code. I think it contains artifacts from other projects, such as `pytorch3d` package, which is not imported in any part of this repository. It also has missing packages, such as numpy, matplotlib etc.
- The fact that some modules were missing in your `requirements.txt` makes me think that you might have used an additional package manager to `pip`, such as `conda`. If that is the case, providing a conda setup file with `conda env export --from-history > environment.yaml` might already solve many headaches!
- I have also spent some time trying to create a fresh environment and install the requirements one by one as the interpreter throws errors, but the openmmlab dependencies are causing a lot of headache, because multiple packages need agreeing versions, and pip does not complain about version mismatch, so a lot of trial and error is needed. Another problem I run into is, I have to guess missing package versions, such as numpy and matplotlib, because apparently latest versions of these are not compatible with the current repository.
- Would you please consider preparing a fresh environment for your code, and document the steps so that others can follow along?
Thanks and best regards,

**Comment by feixue94** [comment]
Hi,

please make sure that colmap, pycolmap, torch and mmsegmentation, mmcv are installed. Especially for mmsegmentation and mmcv, their versions should match the version of torch and cuda (find more details from https://mmcv.readthedocs.io/en/latest/get_started/installation.html and https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/get_started.md) .  It would be better to test them after installation. After these packages are installed, other packages like numpy can be installed directly with pip.

**Comment by kkaytekin** [comment]
Thanks!
