### ISSUE TITLE
test file

### ISSUE THREAD

**Issue by Leaf-G** [feixue94/sfd2#4]
In test_aachenv_1_1 file, this 'matcher = NNM' is a invalid choice of conf. I wanna konw the reason. Should I choose from 'superglue', 'superglue-fast', 'NN-superpoint', 'NN-ratio', 'NN-mutual', 'adalam'? Or is there error where I don't konw?

**Comment by feixue94** [comment]
We used hloc from HFNet for reconstruction and now it has been added to the repository. NNM is supported.

**Comment by Leaf-G** [comment]
thanks
